baseURL = "http://blog.simonhearne.co.uk/"
languageCode = "en-us"
theme = "hyde"
title = "Simon Hearne's Blog"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = "theme-base-0e"
